# Generated by Django 5.1.4 on 2025-06-29 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_debit', models.BooleanField(default=True, verbose_name='Is Debit')),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.accounttype', verbose_name='Account Type')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_settings.currency', verbose_name='Currency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Finance.chartofaccounts', verbose_name='Parent Account')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Chart of Accounts',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Finance.costcenter', verbose_name='Parent Cost Center')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('doc_num', models.CharField(max_length=20, unique=True, verbose_name='Document Number')),
                ('posting_date', models.DateField(verbose_name='Posting Date')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Is Posted')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Debit')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Credit')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.costcenter', verbose_name='Cost Center')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_settings.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('posting_date', models.DateField(verbose_name='Posting Date')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit Amount')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Credit Amount')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.chartofaccounts', verbose_name='Account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Finance.costcenter', verbose_name='Cost Center')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_settings.currency', verbose_name='Currency')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'General Ledger',
                'verbose_name_plural': 'General Ledger',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit Amount')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Credit Amount')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.chartofaccounts', verbose_name='Account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Finance.journalentry', verbose_name='Journal Entry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
            },
        ),
    ]
