# Generated by Django 4.2.20 on 2025-05-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Business Partner Group',
                'verbose_name_plural': 'Business Partner Groups',
            },
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bp_type', models.CharField(blank=True, choices=[('C', 'Customer'), ('S', 'Supplier')], default='C', max_length=1, null=True, verbose_name='Type')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Credit Limit')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Balance')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('federal_tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Federal Tax ID')),
                ('default_billing_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing Street')),
                ('default_billing_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Billing City')),
                ('default_billing_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Billing State')),
                ('default_billing_zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Billing ZIP Code')),
                ('default_billing_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Billing Country')),
                ('default_shipping_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Street')),
                ('default_shipping_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipping City')),
                ('default_shipping_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipping State')),
                ('default_shipping_zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping ZIP Code')),
                ('default_shipping_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipping Country')),
                ('default_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name')),
                ('default_contact_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Position')),
                ('default_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('default_contact_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Mobile')),
                ('default_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Longitude')),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Place ID')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='global_settings.currency', verbose_name='Currency')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusinessPartnerMasterData.businesspartnergroup', verbose_name='Group')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_partners', to='global_settings.paymentterms', verbose_name='Payment Terms')),
            ],
            options={
                'verbose_name': 'Business Partner',
                'verbose_name_plural': 'Business Partners',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1, verbose_name='Address Type')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='BusinessPartnerMasterData.businesspartner', verbose_name='Business Partner')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='FinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Credit Limit')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Balance')),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='BusinessPartnerMasterData.businesspartner', verbose_name='Business Partner')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='global_settings.paymentterms', verbose_name='Payment Terms')),
            ],
            options={
                'verbose_name': 'Financial Information',
                'verbose_name_plural': 'Financial Information',
                'indexes': [models.Index(fields=['business_partner'], name='BusinessPar_busines_275cbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Position')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='BusinessPartnerMasterData.businesspartner', verbose_name='Business Partner')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'indexes': [models.Index(fields=['business_partner'], name='BusinessPar_busines_7bd6f4_idx'), models.Index(fields=['is_default'], name='BusinessPar_is_defa_592f14_idx'), models.Index(fields=['name'], name='BusinessPar_name_6b53c2_idx'), models.Index(fields=['email'], name='BusinessPar_email_a29c74_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('federal_tax_id', models.CharField(blank=True, max_length=20, verbose_name='Federal Tax ID')),
                ('business_partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='BusinessPartnerMasterData.businesspartner', verbose_name='Business Partner')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'indexes': [models.Index(fields=['business_partner'], name='BusinessPar_busines_1219ca_idx'), models.Index(fields=['email'], name='BusinessPar_email_eb01f7_idx'), models.Index(fields=['phone'], name='BusinessPar_phone_28406b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['code'], name='BusinessPar_code_188964_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['name'], name='BusinessPar_name_bf5ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['bp_type'], name='BusinessPar_bp_type_f4d902_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['active'], name='BusinessPar_active_cc1079_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['business_partner'], name='BusinessPar_busines_a4722e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['address_type'], name='BusinessPar_address_db2df4_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default'], name='BusinessPar_is_defa_35e993_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='BusinessPar_country_17d3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='BusinessPar_city_da2f93_idx'),
        ),
    ]
