# Generated by Django 5.1.4 on 2025-06-29 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='BOM Code')),
                ('name', models.CharField(max_length=100, verbose_name='BOM Name')),
                ('bom_type', models.CharField(choices=[('Production', 'Production'), ('Sales', 'Sales'), ('Assembly', 'Assembly'), ('Template', 'Template')], default='Production', max_length=20, verbose_name='BOM Type')),
                ('x_quantity', models.DecimalField(decimal_places=6, default=1, max_digits=18, verbose_name='X Quantity')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Draft', max_length=20, verbose_name='Status')),
                ('total_component_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total Component Value')),
                ('other_cost_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Other Cost %')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Additional Cost')),
                ('total_after_discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total After Discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_boms', to='Inventory.item', verbose_name='Product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='Inventory.unitofmeasure', verbose_name='UoM')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Total')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Production.billofmaterials', verbose_name='Bill of Materials')),
            ],
            options={
                'verbose_name': 'BOM Component',
                'verbose_name_plural': 'BOM Components',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Order Number')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Document Date')),
                ('planned_quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Planned Quantity')),
                ('produced_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Produced Quantity')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Released', 'Released'), ('In Process', 'In Process'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='Production.billofmaterials', verbose_name='Bill of Materials')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='Inventory.item', verbose_name='Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='Inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Issue Number')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Document Date')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_issues', to='Inventory.warehouse', verbose_name='Warehouse')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='Production.productionorder', verbose_name='Production Order')),
            ],
            options={
                'verbose_name': 'Production Issue',
                'verbose_name_plural': 'Production Issues',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('planned_quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Planned Quantity')),
                ('issued_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Issued Quantity')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Production.productionorder', verbose_name='Production Order')),
            ],
            options={
                'verbose_name': 'Production Order Component',
                'verbose_name_plural': 'Production Order Components',
            },
        ),
        migrations.CreateModel(
            name='ProductionIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantity')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Production.productionissue', verbose_name='Production Issue')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='Production.productionordercomponent', verbose_name='Production Order Component')),
            ],
            options={
                'verbose_name': 'Production Issue Line',
                'verbose_name_plural': 'Production Issue Lines',
            },
        ),
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('receipt_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Receipt Number')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Document Date')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='Production.productionorder', verbose_name='Production Order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_receipts', to='Inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Production Receipt',
                'verbose_name_plural': 'Production Receipts',
            },
        ),
        migrations.CreateModel(
            name='ProductionReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantity')),
                ('uom', models.CharField(blank=True, max_length=20, null=True, verbose_name='UOM')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Production.productionreceipt', verbose_name='Production Receipt')),
            ],
            options={
                'verbose_name': 'Production Receipt Line',
                'verbose_name_plural': 'Production Receipt Lines',
            },
        ),
    ]
