# Generated by Django 4.2.20 on 2025-05-27 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionreceipt',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProductionReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('item_code', models.CharField(max_length=50, verbose_name='Item Code')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Quantity')),
                ('uom', models.CharField(blank=True, max_length=20, null=True, verbose_name='UOM')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Production.productionreceipt', verbose_name='Production Receipt')),
            ],
            options={
                'verbose_name': 'Production Receipt Line',
                'verbose_name_plural': 'Production Receipt Lines',
            },
        ),
    ]
