# Generated by Django 5.1.4 on 2025-06-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterday',
            name='workplace',
        ),
    ]
