# Generated by Django 5.1.4 on 2025-06-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zkattendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='zkattendancelog',
            name='card_no',
            field=models.CharField(blank=True, help_text='Card number used for authentication, if applicable.', max_length=50, null=True, verbose_name='Card Number'),
        ),
        migrations.AddField(
            model_name='zkattendancelog',
            name='device_serial_no',
            field=models.CharField(blank=True, help_text='Serial number or unique identifier of the device, matching ZKDevice.device_id.', max_length=100, null=True, verbose_name='Device Serial Number'),
        ),
        migrations.AddField(
            model_name='zkattendancelog',
            name='record_id',
            field=models.CharField(blank=True, help_text='Unique record identifier from the device.', max_length=255, null=True, verbose_name='Record ID'),
        ),
        migrations.AddField(
            model_name='zkattendancelog',
            name='reserved',
            field=models.CharField(blank=True, help_text='Device-specific reserved data, if any.', max_length=255, null=True, verbose_name='Reserved Field'),
        ),
        migrations.AddField(
            model_name='zkattendancelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this log was last updated in the database.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this log was saved to the database.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='device',
            field=models.ForeignKey(help_text='The ZKTeco device that recorded this attendance log.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='Hrm.zkdevice', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='punch_type',
            field=models.CharField(blank=True, help_text='Type of punch (e.g., Check In, Check Out, Break In).', max_length=50, null=True, verbose_name='Punch Type'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='status',
            field=models.CharField(blank=True, help_text='Status code or description of the attendance record.', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='timestamp',
            field=models.DateTimeField(help_text='Date and time when the attendance was recorded.', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='user_id',
            field=models.CharField(help_text='Unique identifier of the user as recorded by the device.', max_length=255, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='verify_type',
            field=models.CharField(blank=True, help_text='Method of verification (e.g., Fingerprint, Card, Password).', max_length=50, null=True, verbose_name='Verification Type'),
        ),
        migrations.AlterField(
            model_name='zkattendancelog',
            name='work_code',
            field=models.CharField(blank=True, help_text='Work or task code associated with the attendance.', max_length=255, null=True, verbose_name='Work Code'),
        ),
        migrations.AlterUniqueTogether(
            name='zkattendancelog',
            unique_together={('device', 'user_id', 'timestamp', 'punch_type')},
        ),
        migrations.AddIndex(
            model_name='zkattendancelog',
            index=models.Index(fields=['device', 'user_id', 'timestamp'], name='Hrm_zkatten_device__cc7c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='zkattendancelog',
            index=models.Index(fields=['user_id'], name='Hrm_zkatten_user_id_37b520_idx'),
        ),
        migrations.AddIndex(
            model_name='zkattendancelog',
            index=models.Index(fields=['timestamp'], name='Hrm_zkatten_timesta_4e43f5_idx'),
        ),
        migrations.AddIndex(
            model_name='zkattendancelog',
            index=models.Index(fields=['device_serial_no'], name='Hrm_zkatten_device__6a18fc_idx'),
        ),
        migrations.AddIndex(
            model_name='zkattendancelog',
            index=models.Index(fields=['record_id'], name='Hrm_zkatten_record__e91c26_idx'),
        ),
    ]
