# Generated by Django 5.1.4 on 2025-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0002_alter_zkattendancelog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkdevice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
    ]
