# Generated by Django 5.1.4 on 2025-06-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0002_remove_rosterday_workplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycomponent',
            options={'ordering': ['component_type', 'name'], 'verbose_name': 'Salary Component', 'verbose_name_plural': 'Salary Components'},
        ),
        migrations.AlterModelOptions(
            name='salarystructurecomponent',
            options={'ordering': ['salary_structure__employee__first_name', 'component__component_type', 'component__name'], 'verbose_name': 'Salary Structure Component', 'verbose_name_plural': 'Salary Structure Components'},
        ),
        migrations.AddField(
            model_name='employeesalarystructure',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base salary amount before allowances', max_digits=10, verbose_name='Basic Salary'),
        ),
        migrations.AddField(
            model_name='employeesalarystructure',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final salary after deductions', max_digits=10, verbose_name='Net Salary'),
        ),
        migrations.AddField(
            model_name='employeesalarystructure',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all deduction components', max_digits=10, verbose_name='Total Deductions'),
        ),
        migrations.AddField(
            model_name='employeesalarystructure',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all earning components', max_digits=10, verbose_name='Total Earnings'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='calculated_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final calculated amount', max_digits=10, verbose_name='Calculated Amount'),
        ),
        migrations.AddField(
            model_name='salarystructurecomponent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='employeesalarystructure',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total salary including all earnings', max_digits=10, verbose_name='Gross Salary'),
        ),
        migrations.AlterField(
            model_name='salarystructurecomponent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for this component', max_digits=10, null=True, verbose_name='Fixed Amount'),
        ),
        migrations.AlterField(
            model_name='salarystructurecomponent',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of basic/gross salary', max_digits=5, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterUniqueTogether(
            name='salarystructurecomponent',
            unique_together={('salary_structure', 'component')},
        ),
    ]
