# Generated by Django 5.1.4 on 2025-07-01 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gross_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Gross Salary'),
        ),
    ]
