# Generated by Django 5.1.4 on 2025-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0003_employee_gross_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Name"),
        ),
    ]
