# Generated by Django 5.1.4 on 2025-06-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0003_zkdevice_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='Hrm.shift', verbose_name='Default Shift'),
        ),
    ]
