# Generated by Django 5.1.4 on 2025-07-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0004_employee_father_name_employee_mother_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='employee_documents/', verbose_name='File')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='present_address',
        ),
        migrations.AddField(
            model_name='employee',
            name='education_qualification',
            field=models.CharField(blank=True, choices=[('PSC', 'PSC/Five Pass'), ('JSC', 'JSC/Eight Pass'), ('SSC', 'S.S.C'), ('HSC', 'H.S.C'), ('GRAD', 'Graduation'), ('DIPLOMA', 'Diploma'), ('OTHERS', 'Others')], max_length=50, null=True, verbose_name='Educational Qualification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_care_of',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Care Of'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_home_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Home Phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_post_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_union',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Union'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_upazila_thana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila/Thana'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mailing_village_town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Village/Town/Road/House/Flat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='major_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Major Subject/Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nid_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NID No'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passing Year'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_care_of',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Care Of'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_home_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Home Phone'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_post_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Post Code'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_post_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_union',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Union'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_upazila_thana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Upazila/Thana'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_village_town',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Village/Town/Road/House/Flat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity')], default='Islam', max_length=50, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='employee',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='employee',
            name='university_board',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University/Board'),
        ),
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='employees', to='Hrm.document'),
        ),
    ]
