# Generated by Django 5.1.4 on 2025-06-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0004_employee_default_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
    ]
