# Generated by Django 4.2.20 on 2025-05-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hrm', '0004_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationattendance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Location Attendance', 'verbose_name_plural': 'Location Attendances'},
        ),
        migrations.AlterModelOptions(
            name='userlocation',
            options={'ordering': ['user__username', 'location__name'], 'verbose_name': 'User Location', 'verbose_name_plural': 'User Locations'},
        ),
        migrations.AddField(
            model_name='locationattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Radius (km)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='attendance_type',
            field=models.CharField(choices=[('IN', 'Check-in'), ('OUT', 'Check-out')], max_length=3, verbose_name='Attendance Type'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='device_info',
            field=models.TextField(blank=True, null=True, verbose_name='Device Info'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='is_within_radius',
            field=models.BooleanField(default=False, verbose_name='Is Within Radius'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Hrm.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='locationattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_attendances', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to='Hrm.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
