# Generated by Django 4.2.20 on 2025-05-20 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0005_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField()),
                ('total_days', models.DecimalField(decimal_places=2, help_text='Total allocated days for this leave type', max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, help_text='Days used so far', max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, help_text='Days in pending leave applications', max_digits=6)),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=0, help_text='Days carried forward from previous year', max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='Hrm.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='Hrm.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
