# Generated by Django 4.2.20 on 2025-05-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hrm', '0006_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('port', models.IntegerField(default=4370, verbose_name='Port')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('timeout', models.IntegerField(default=5, verbose_name='Connection Timeout (seconds)')),
                ('password', models.CharField(blank=True, help_text='Leave blank if no password is set on the device', max_length=100, null=True, verbose_name='Device Password')),
                ('force_udp', models.BooleanField(default=False, help_text='Use UDP instead of TCP for connection', verbose_name='Force UDP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'ZK Device',
                'verbose_name_plural': 'ZK Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZKAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='User ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('punch_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Punch Type')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Status Code')),
                ('verify_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Verification Type')),
                ('work_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='Hrm.zkdevice')),
            ],
            options={
                'verbose_name': 'ZK Attendance Log',
                'verbose_name_plural': 'ZK Attendance Logs',
                'ordering': ['-timestamp'],
                'unique_together': {('device', 'user_id', 'timestamp')},
            },
        ),
    ]
