# Generated by Django 5.1.4 on 2025-06-29 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusinessPartnerMasterData', '0001_initial'),
        ('Finance', '0001_initial'),
        ('Sales', '0001_initial'),
        ('global_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Payment Method')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('doc_num', models.CharField(max_length=20, unique=True, verbose_name='Document Number')),
                ('payment_type', models.CharField(choices=[('incoming', 'Incoming Payment'), ('outgoing', 'Outgoing Payment')], max_length=10, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Is Reconciled')),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusinessPartnerMasterData.businesspartner', verbose_name='Business Partner')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='global_settings.currency', verbose_name='Currency')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.salesorder', verbose_name='Sales Order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Banking.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Finance.chartofaccounts', verbose_name='Account')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lines', to='Banking.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Line',
                'verbose_name_plural': 'Payment Lines',
            },
        ),
    ]
