# Generated by Django 5.1.4 on 2025-06-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_inventorytransaction_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='Inventory.warehouse', verbose_name='Warehouse'),
        ),
    ]
