# Generated by Django 5.1.4 on 2025-06-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-document_date', '-created_at'], 'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='document_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document No'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='due_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Due Amount'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payable_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Payable Amount'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Total Amount'),
        ),
    ]
